name: Linters

on:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  NODE_VERSION: lts/*

permissions:
  contents: read

jobs:
  yarn-run-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Extract Uppy version from yarn.lock
        id: UPPY_VERSION_FROM_YARN_LOCK
        run: |
          grep 'resolution: "uppy@' yarn.lock | awk -F'"' '{ sub(/npm:/, ""); print "UPPY_REF=" $2 }' >> "$GITHUB_OUTPUT"
      - name: Checkout docs from Uppy repo
        uses: actions/checkout@v4
        with:
          repository: transloadit/uppy
          ref: ${{ steps.UPPY_VERSION_FROM_YARN_LOCK.outputs.UPPY_REF }}
          path: uppy
      - run: mv uppy /tmp/uppy && ln -s /tmp/uppy/docs docs
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
        env:
          SKIP_YARN_COREPACK_CHECK: 1
      - name: Environment Information
        run: npx envinfo
      - name: Install dependencies
        run: corepack yarn --immutable
      - name: Lint files
        run: corepack yarn lint
