name: Test build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  merge_group:
    types: [checks_requested]

env:
  NODE_VERSION: lts/*

concurrency: test-${{ github.ref }}

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
        env:
          SKIP_YARN_COREPACK_CHECK: 1

      - name: Install dependencies
        run: corepack yarn install --immutable
      - name: Test build website
        run: corepack yarn build
