name: Test build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: test-${{ github.ref }}

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: corepack yarn install --immutable
      - name: Test build website
        run: corepack yarn build
