name: Test build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  merge_group:
    types: [checks_requested]

env:
  NODE_VERSION: lts/*

concurrency: test-${{ github.ref }}

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract Uppy version from yarn.lock
        id: UPPY_VERSION_FROM_YARN_LOCK
        run: |
          grep 'resolution: "uppy@' yarn.lock | awk -F'"' '{ sub(/npm:/, ""); print "UPPY_REF=" $2 }' >> "$GITHUB_OUTPUT"
      - name: Checkout docs from Uppy repo
        uses: actions/checkout@v4
        with:
          repository: transloadit/uppy
          ref: ${{ steps.UPPY_VERSION_FROM_YARN_LOCK.outputs.UPPY_REF }}
          path: uppy
      - run: mv uppy /tmp/uppy && ln -s /tmp/uppy/docs docs
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
        env:
          SKIP_YARN_COREPACK_CHECK: 1

      - name: Install dependencies
        run: corepack yarn install --immutable
      - name: Test build website
        run: corepack yarn build
